export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

// user
export const USER_CREATE_CHANGE_USERNAME = "USER_CREATE_CHANGE_USERNAME";
export const USER_CREATE_CHANGE_PASSWORD = "USER_CREATE_CHANGE_PASSWORD";
export const USER_CREATE_STATUS = "USER_CREATE_STATUS";
export const USER_CREATE = "USER_CREATE";